---
#
- name: configure firewall
  firewalld:
    port: "{{ item }}"
    permanent: yes
    immediate: yes
    state: enabled
  loop:
    - "{{ splunk.web_port }}/tcp"
    - "{{ splunk.mgmt_port }}/tcp"
    - "{{ splunk.forwarder_port}}/tcp"
  tags:
    - firewall

