- name: configure deployment client
  template:
    src: templates/ds_client.j2
    dest: "{{ splunk.splunk_base }}/etc/system/local/deploymentclient.conf"
    owner: "{{ splunk.user }}" 
    group: "{{ splunk.group }}"
    mode: 0640
  tags:
    - ds_client

